### ISSUE TITLE
Update required?

### ISSUE THREAD

**Issue by darthbane72** [jwinget/fvtt-module-critterdb-import#4]
JUst downlaoded this mod and was attempting to import a beastiary. recieved "Required feild img not present in PrototypeToken"

**Comment by jwinget** [comment]
Which version of Foundry are you running?
I haven't tested this module with 0.7x yet, and will likely get to that next week.

**Comment by darthbane72** [comment]
running 0.7.5 with Dnd 5e .98

**Comment by 749** [comment]
Still exists in 0.7.7 with DnD5e 1.1.1
Happens when the critter db export has `"imageUrl": "",`

**Comment by TrueBrujah** [comment]
we have the same Problem on 0.7.7  pls.

**Comment by jwinget** [comment]
This should be fixed in release 1.0.4, which I just pushed.
Please update your module within Foundry and let me know if there are still issues.

Sorry for the delay.
